### ISSUE TITLE
Cannot "yarn start"

### ISSUE THREAD

**Issue by jakubklimek** [prixladi/treeloc-frontend#1]
```
C:\Users\Kuba\Documents\GitHub\prix\treeloc-frontend>yarn start
yarn run v1.12.3
$ react-scripts start
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by prixladi** [comment]
Nejdříve je potřeba pustit 'yarn' aby se stahly balíčky

**Comment by jakubklimek** [comment]
OK, to funguje. Pak to musí být v readme. Teď se dívám, že už je tam pouze docker-compose. Tedy přes yarn už to podporovaný způsob není?

**Comment by prixladi** [comment]
Yarn používám při vývoji. Doplním to readme, to readme co tam bylo předtím je automaticky generované při inicializaci přes 'yarn create-react-app'

**Comment by prixladi** [comment]
https://github.com/prixladi/treeloc-frontend/blob/master/README.md
